name: PHP Elastic Beanstalk Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: false
        default: ${{ github.ref }}
        type: string
      workingDirectory:
        required: false
        default: '.'
        type: string
      phpVersion:
        required: true
        type: string
      elasticBeanstalkApplication:
        required: true
        type: string
      packageJsonPath:
        required: true
        type: string
      hasDevelopmentEnvironment:
        required: false
        default: false
        type: boolean
jobs:
  php-elasticbeanstalk-build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3 (needed for eb cli)
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.*"
      - name: Setup PHP
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) }}
        uses: shivammathur/setup-php@2.21.1
        with:
          php-version: ${{ inputs.phpVersion }}
          tools: composer:v2
      - name: Get composer cache directory
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) }}
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer dependencies
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) }}
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-no-dev-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-no-dev-
      - name: Install Composer dependencies
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) }}
        run: composer install --no-dev
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{ inputs.packageJsonPath }}
      - name: Install dependencies
        run: npm install
      - name: Build Application
        id: build
        run: npm run prod
      - name: Send Teams notification for failed build
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "text": "FAILED: Deployment to ${{ inputs.environment }} for ${{ github.repository }} ${{ inputs.branch }} branch failed due to build failure. Build needs to be fixed."
            }
      - name: Deploy to Elastic Beanstalk (Development)
        id: deployDevelopment
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true && inputs.environment == 'qa' && inputs.hasDevelopmentEnvironment) }}
        run: |
          echo "Installing Elastic Beanstalk Cli"
          pip install awsebcli==3.19 --upgrade

          NOW=$(date +"%m%d%Y_%H%M")
          BRANCH_DETAIL="${{ inputs.branch }}"
          strarr=($(echo $BRANCH_DETAIL | tr "\/" "\n"))
          COUNT=${#strarr[@]}
          if [[ $COUNT -gt 1 ]]
          then
            BRANCH_DETAIL=${strarr[1]}
          fi

          eb deploy --timeout 20 ${{ inputs.elasticBeanstalkApplication }}-development -l $(printf "%s_%s" "$BRANCH_DETAIL" "$NOW")
      - name: Send Teams notification for failed deployment
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ failure() && inputs.environment != false && (github.event.pull_request.merged == true && inputs.environment == 'qa') && steps.deployDevelopment.conclusion == 'failure' && inputs.hasDevelopmentEnvironment }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "text": "FAILED: Deployment to development for ${{ github.repository }} ${{ inputs.branch }} branch failed during the deployment phase. See workflow for more information"
            }
      - name: Send Teams notification for successful deployment
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ success() && inputs.environment != false && (github.event.pull_request.merged == true && inputs.environment == 'qa' && inputs.hasDevelopmentEnvironment) }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "text": "Deploying ${{ github.repository }} ${{ inputs.branch }} to development has completed"
            }
      - name: Deploy to Elastic Beanstalk
        id: deploy1
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) }}
        run: |
          echo "Installing Elastic Beanstalk Cli"
          pip install awsebcli==3.19 --upgrade

          NOW=$(date +"%m%d%Y_%H%M")
          BRANCH_DETAIL="${{ inputs.branch }}"
          strarr=($(echo $BRANCH_DETAIL | tr "\/" "\n"))
          COUNT=${#strarr[@]}
          if [[ $COUNT -gt 1 ]]
          then
            BRANCH_DETAIL=${strarr[1]}
          fi

          eb deploy --timeout 20 ${{ inputs.elasticBeanstalkApplication }}-${{ inputs.environment }} -l $(printf "%s_%s" "$BRANCH_DETAIL" "$NOW")
      - name: Send Teams notification for failed deployment
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ failure() && inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) && steps.deploy1.conclusion == 'failure' }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "text": "FAILED: Deployment to ${{ inputs.environment }} for ${{ github.repository }} ${{ inputs.branch }} branch failed during the deployment phase. See workflow for more information"
            }
      - name: Send Teams notification for successful deployment
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ success() && inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production' || (inputs.environment == 'staging' && github.event_name == 'push')) }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "text": "Deploying ${{ github.repository }} ${{ inputs.branch }} to ${{ inputs.environment }} has completed"
            }
