name: Yarn Build
on:
  workflow_call:
    inputs:      
      packageJsonPath:
        required: true
        type: string     
      workingDirectory:
        description: The root directory for the frontend code base
        required: false
        default: '.'
        type: string       
jobs:
  yarn-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:  
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: ${{ inputs.packageJsonPath }}
      - name: Install dependencies
        run: yarn install --immutable
     
