name: yarn deploy
on:
  workflow_call:
    inputs:
      DISTRIBUTION_ID_KEY:
        required: true
        type: string      
      environment:
        required: true
        type: string
      workingDirectory:
        description: The root directory for the frontend code base
        required: false
        default: '.'
        type: string
      directoryToDeploy:
        required: true
        type: string
      directoryToDeployTo:
        required: true
        type: string
      branch:
        required: false
        default: ${{ github.ref }}
        type: string

jobs:
  yarn-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}      
      - name: Deploy Remote Entry with no caching headers
        id: deploy1
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production') }}
        run: aws s3 sync ${{ inputs.directoryToDeploy }} s3://bu-static-sites/${{ inputs.environment }}/${{ inputs.directoryToDeployTo }} --delete --exact-timestamps --cache-control no-store,max-age-0 --exclude "*" --include "remoteEntry.js"
      - name: Deploy rest of files
        id: deploy2
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production') }}
        run: aws s3 sync ${{ inputs.directoryToDeploy }} s3://bu-static-sites/${{ inputs.environment }}/${{ inputs.directoryToDeployTo }} --delete --exact-timestamps --include "*" --exclude "remoteEntry.js"
      - name: Invalidate Cloudfront cache
        id: deploy3
        if: ${{ inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production') }}
        run: aws cloudfront create-invalidation --distribution-id "${{ secrets[inputs.DISTRIBUTION_ID_KEY] }}" --paths "/*"
      - name: Send Teams notification for failed build
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ failure() && inputs.environment != false && (github.event.pull_request.merged == true || inputs.environment == 'production') && (steps.deploy1.conclusion == 'failure' || steps.deploy2.conclusion == 'failure' || steps.deploy3.conclusion == 'failure') }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "text": "FAILED: Deployment to ${{ inputs.environment }} for ${{ github.repository }} ${{ inputs.branch }} branch failed during the deployment phase. See workflow for more information."
            }
      - name: Send Teams notification for successfull deployment
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ success() && (github.event.pull_request.merged == true || inputs.environment == 'production') }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "text": "Deploying ${{ github.repository }} ${{ inputs.branch }} to ${{ inputs.environment }} has completed."
            }
